wtf:
  colors:
    background: black
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
    checked: yellow
    highlight:
      fore: black
      back: gray
    rows:
      even: yellow
      odd: white
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # four columns, each of which are 35 characters wide.
    columns: [35, 35, 35, 35]
    # How _high_ the rows are, in terminal lines. In this case we have four rows
    # that support ten line of text and one of four.
    rows: [10, 10, 10, 10, 4]
  refreshInterval: 1
  openFileUtil: "open"
  mods:
    # You can have multiple widgets of the same type.
    # The "key" is the name of the widget and the type is the actual
    # widget you want to implement.
    europe_time:
      title: "⏲"
      type: clocks
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Madrid: "Europe/Madrid"
        UTC: "Etc/UTC"
        GMT: "Etc/GMT"
        London: "Europe/London"
        Paris: "Europe/Paris"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    battery:
      type: power
      title: "⚡"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
    todolist:
      type: todo
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "black"
          back: "orange"
      enabled: true
      filename: "notes.md"
      position:
        top: 1
        left: 0
        height: 2
        width: 1
      refreshInterval: 3600
    resources:
      type: resourceusage
      enabled: true
      position:
        top: 1
        left: 1
        height: 2
        width: 1
      refreshInterval: 1
    uptime:
      type: cmdrunner
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 3
      refreshInterval: 30
    disks:
      title: "💽"
      type: cmdrunner
      cmd: "df"
      args: ["-h", "--type", "ext4", "--type", nfs4"]
      enabled: true
      position:
        top: 1
        left: 2
        height: 2
        width: 3
      refreshInterval: 3600
