#
# Executes commands at login post-zshrc.
#

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh

# Aliases
for f in ~/.dotfiles/zsh/aliases/*; do source $f; done

# Execute code that does not affect the current session in the background.
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${ZDOTDIR:-$HOME}/.zcompdump"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
    zcompile "$zcompdump"
  fi
} &!

# Enable menu for selection

zstyle ':completion:*' menu select=2
setopt  autocd

# Prompt

zplugin ice depth=1; zplugin light romkatv/powerlevel10k

# Using bat to handle manpages

export MANPAGER="sh -c 'col -b | bat -l man -p'"
