#
# Defines environment variables.
#

# Secrets in env variables should go to a different file
source ~/.dotfiles/zsh/zsecrets

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export TERM=xterm-256color
export CLICOLOR=1

export PATH=$HOME/bin:$PATH:/usr/local/share/npm/bin:$HOME/.rvm/bin:$HOME/.cargo/bin

# To enable syntax highlight in less first you need to brew install source-highlight
export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS=" -R "

# -----------
# Emacs
# -----------
export EDITOR="emacsclient --no-wait -c"
export VISUAL="emacsclient --no-wait -c"

# -----------
# Go settings
# -----------
export GOPATH=$HOME/code/Go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin

export JIRA_DEFAULT_ACTION="dashboard"
