#
# Executes commands at the start of an interactive session.
#


# ------------
# Configure ZSH
# -------------

if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi
HISTSIZE=20000
SAVEHIST=20000

# Show history
case $HIST_STAMPS in
  "mm/dd/yyyy") alias history='fc -fl 1' ;;
  "dd.mm.yyyy") alias history='fc -El 1' ;;
  "yyyy-mm-dd") alias history='fc -il 1' ;;
  *) alias history='fc -l 1' ;;
esac

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

unsetopt AUTO_NAME_DIRS

fpath=(/usr/local/share/zsh-completions $HOME/.dotfiles/zsh/completions $fpath)

autoload -U compinit
compinit


# ----------
# Android
# ----------

export ANDROID_HOME=/usr/local/opt/android-sdk

# ---------
# Node
# ---------

export NVM_DIR="/Users/rafael/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

# ---------
# ZPlug
# ---------

zplug "zplug/zplug"
zplug "b4b4r07/emoji-cli"
zplug "zsh-users/zsh-syntax-highlighting", defer:2

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load --verbose


#---------
# Elixir
#---------


test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

###-tns-completion-start-###
if [ -f /Users/rafael/.tnsrc ]; then
    source /Users/rafael/.tnsrc
fi
###-tns-completion-end-###

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/rafael/.nvm/versions/node/v8.7.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/rafael/.nvm/versions/node/v8.7.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/rafael/.nvm/versions/node/v8.7.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/rafael/.nvm/versions/node/v8.7.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/rafael/bin/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/rafael/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/rafael/bin/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/rafael/bin/google-cloud-sdk/completion.zsh.inc'; fi
