#
# Executes commands at the start of an interactive session.
#

# instaprompt on p10k. Should be at the beginning

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# ------------
# Configure ZSH
# -------------

if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi
HISTSIZE=20000
SAVEHIST=20000

# Show history
case $HIST_STAMPS in
  "mm/dd/yyyy") alias history='fc -fl 1' ;;
  "dd.mm.yyyy") alias history='fc -El 1' ;;
  "yyyy-mm-dd") alias history='fc -il 1' ;;
  *) alias history='fc -l 1' ;;
esac

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

unsetopt AUTO_NAME_DIRS

fpath=(/usr/local/share/zsh-completions $HOME/.dotfiles/zsh/completions $fpath)

source "$HOME/.zplugin/bin/zplugin.zsh"

zplugin ice wait'0a' lucid blockf
zplugin load zsh-users/zsh-completions

zplugin ice wait'2' lucid blockf
zplugin load "zsh-users/zsh-history-substring-search"

zplugin ice wait"2" atinit"zpcompinit; zpcdreplay"
zplugin light "zdharma/fast-syntax-highlighting"

zplugin ice as"docker-completion"
zplugin snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker

zplugin ice as"docker-compose-completion"
zplugin snippet https://github.com/docker/compose/blob/master/contrib/completion/zsh/_docker-compose

zplugin ice as"docker-machine-completion"
zplugin snippet https://github.com/docker/machine/blob/master/contrib/completion/zsh/_docker-machine

if [ -f /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh ]; then
  source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fi

# ----------
# Android
# ----------

export ANDROID_HOME=/usr/local/opt/android-sdk

# ---------
# Node
# ---------

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"


#---------
# Elixir
#---------


test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"


###-tns-completion-start-###
if [ -f ~/.tnsrc ]; then
    source /Users/rafael/.tnsrc
fi
###-tns-completion-end-###

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Pyenv changes
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Direnv
eval "$(direnv hook zsh)"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

autoload -Uz _zplugin
(( ${+_comps} )) && _comps[zplugin]=_zplugin

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
